baseURL = "https://www.locallyoptimistic.com/"
title = "Locally Optimistic"
theme = "hugo-nuo"

Paginate = 5
preserveTaxonomyNames = true
languageCode = "en"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyURLs = false

disqusShortname = "locallyoptimistic"
googleAnalytics = "UA-345857-22"
copyright = "Â© The text of this post is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License (CC BY-NC-ND 4.0). Images (including the LocallyOptimistic logo) are the property of LocallyOptimistic and should NOT be copied, reproduced, or remixed without explicit prior approval from Locally Optimistic. See our licensing page (locallyoptimistic.com/licensing) for more information." 

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Locally Optimistic"
  avatar = "/img/logo.png"
  seotitle = "Locally Optimistic"
  subtitle = "A blog about data organizations"
  description = "Locally Optimistic is a blog for current and aspiring data analytics leaders"
  paginate = 10

  github = "locallyoptimistic/LocallyOptimistic"
  twitter = "localoptimistic"
