baseURL = "https://www.locallyoptimistic.com/"
title = "Locally Optimistic"
theme = "hugo-nuo"

Paginate = 5
preserveTaxonomyNames = true
languageCode = "en"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyURLs = false

disqusShortname = "locallyoptimistic"
googleAnalytics = "UA-345857-22"
copyright = "Â© Locally Optimistic"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Tags"
  weight = 30
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "Locally Optimistic"
  avatar = "/img/logo.png"
  seotitle = "Locally Optimistic"
  subtitle = " "
  description = "Locally Optimistic is a blog for current and aspiring data analytics leaders"
  paginate = 10

  github = "locallyoptimistic/LocallyOptimistic"
  twitter = "localoptimistic"
